/**
 * Turkiye il / ilce verisi ve OpenStreetMap (Nominatim) yardimci fonksiyonlari.
 *
 * Butun 81 il ve genis bir ilce listesi icerir. Mahalleler (ve acik adresten
 * koordinat) icin OpenStreetMap'in ucretsiz Nominatim API'sine baglanilir.
 * Nominatim servisine ulasilamadiginda kullanici manuel giris yapabilir.
 */

export const TR_PROVINCES_MAP: Record<string, string[]> = {
  Adana: [
    "Aladag",
    "Ceyhan",
    "Cukurova",
    "Feke",
    "Imamoglu",
    "Karaisali",
    "Karatas",
    "Kozan",
    "Pozanti",
    "Saimbeyli",
    "Saricam",
    "Seyhan",
    "Tufanbeyli",
    "Yumurtalik",
    "Yuregir",
  ],
  Adiyaman: [
    "Besni",
    "Celikhan",
    "Gerger",
    "Golbasi",
    "Kahta",
    "Merkez",
    "Samsat",
    "Sincik",
    "Tut",
  ],
  Afyonkarahisar: [
    "Basmakci",
    "Bayat",
    "Bolvadin",
    "Cay",
    "Cobanlar",
    "Dazkiri",
    "Dinar",
    "Emirdag",
    "Evciler",
    "Hocalar",
    "Ihsaniye",
    "Iscehisar",
    "Kiziloren",
    "Merkez",
    "Sandikli",
    "Sinanpasa",
    "Sultandagi",
    "Sultanyayla",
  ],
  Agri: [
    "Diyadin",
    "Dogubayazit",
    "Eleskirt",
    "Hamur",
    "Merkez",
    "Patnos",
    "Taslicay",
    "Tutak",
  ],
  Aksaray: [
    "Agacoren",
    "Eskil",
    "Gulagac",
    "Guzelyurt",
    "Merkez",
    "Ortakoy",
    "Sariyahsi",
    "Sultanhani",
  ],
  Amasya: [
    "Goynucek",
    "Gumushacikoy",
    "Hamamozu",
    "Merkez",
    "Merzifon",
    "Suluova",
    "Tasova",
  ],
  Ankara: [
    "Akyurt",
    "Altindag",
    "Ayas",
    "Bala",
    "Beypazari",
    "Camlidere",
    "Cankaya",
    "Cubuk",
    "Elmadag",
    "Etimesgut",
    "Evren",
    "Golbasi",
    "Gudul",
    "Haymana",
    "Kahramankazan",
    "Kalecik",
    "Kecioren",
    "Kizilcahamam",
    "Mamak",
    "Nallihan",
    "Polatli",
    "Pursaklar",
    "Sincan",
    "Sereflikochisar",
    "Yenimahalle",
  ],
  Antalya: [
    "Akseki",
    "Aksu",
    "Alanya",
    "Demre",
    "Dosemealti",
    "Elmali",
    "Finike",
    "Gazipasa",
    "Gundogmus",
    "Ibradi",
    "Kas",
    "Kemer",
    "Kepez",
    "Konyaalti",
    "Korkuteli",
    "Kumluca",
    "Manavgat",
    "Muratpasa",
    "Serik",
  ],
  Ardahan: ["Cildir", "Damal", "Gole", "Hanak", "Merkez", "Posof"],
  Artvin: [
    "Ardanuc",
    "Arhavi",
    "Borcka",
    "Hopa",
    "Kemalpasa",
    "Merkez",
    "Murgul",
    "Savsat",
    "Yusufeli",
  ],
  Aydin: [
    "Bozdogan",
    "Buharkent",
    "Cine",
    "Didim",
    "Efeler",
    "Germencik",
    "Incirliova",
    "Karacasu",
    "Karpuzlu",
    "Kocarli",
    "Kosk",
    "Kusadasi",
    "Kuyucak",
    "Nazilli",
    "Sultanhisar",
    "Soke",
    "Yenipazar",
  ],
  Balikesir: [
    "Altieylul",
    "Ayvalik",
    "Balya",
    "Bandirma",
    "Bigadic",
    "Burhaniye",
    "Dursunbey",
    "Edremit",
    "Erdek",
    "Gomec",
    "Gonen",
    "Havran",
    "Ivrindi",
    "Karesi",
    "Kepsut",
    "Manyas",
    "Marmara",
    "Savastepe",
    "Sindirgi",
    "Susurluk",
  ],
  Bartin: ["Amasra", "Kurucasile", "Merkez", "Ulus"],
  Batman: [
    "Besiri",
    "Gercus",
    "Hasankeyf",
    "Kozluk",
    "Merkez",
    "Sason",
  ],
  Bayburt: ["Aydintepe", "Demirozu", "Merkez"],
  Bilecik: [
    "Bozuyuk",
    "Golpazari",
    "Inhisar",
    "Merkez",
    "Osmaneli",
    "Pazaryeri",
    "Sogut",
    "Yenipazar",
  ],
  Bingol: [
    "Adakli",
    "Genc",
    "Karliova",
    "Kigi",
    "Merkez",
    "Solhan",
    "Yayladere",
    "Yedisu",
  ],
  Bitlis: [
    "Adilcevaz",
    "Ahlat",
    "Guroymak",
    "Hizan",
    "Merkez",
    "Mutki",
    "Tatvan",
  ],
  Bolu: [
    "Dortdivan",
    "Gerede",
    "Goynuk",
    "Kibriscik",
    "Mengen",
    "Merkez",
    "Mudurnu",
    "Seben",
    "Yenicaga",
  ],
  Burdur: [
    "Agalsun",
    "Altinyayla",
    "Bucak",
    "Cavdir",
    "Celtikci",
    "Golhisar",
    "Karamanli",
    "Kemer",
    "Merkez",
    "Tefenni",
    "Yesilova",
  ],
  Bursa: [
    "Buyukorhan",
    "Gemlik",
    "Gursu",
    "Harmancik",
    "Inegol",
    "Iznik",
    "Karacabey",
    "Keles",
    "Kestel",
    "Mudanya",
    "Mustafakemalpasa",
    "Nilufer",
    "Orhaneli",
    "Orhangazi",
    "Osmangazi",
    "Yenisehir",
    "Yildirim",
  ],
  Canakkale: [
    "Ayvacik",
    "Bayramic",
    "Biga",
    "Bozcaada",
    "Can",
    "Eceabat",
    "Ezine",
    "Gelibolu",
    "Gokceada",
    "Lapseki",
    "Merkez",
    "Yenice",
  ],
  Cankiri: [
    "Atkaracalar",
    "Bayramoren",
    "Cerkes",
    "Eldivan",
    "Ilgaz",
    "Kizilirmak",
    "Korgun",
    "Kursunlu",
    "Merkez",
    "Orta",
    "Sabanozu",
    "Yaprakli",
  ],
  Corum: [
    "Alaca",
    "Bayat",
    "Bogazkale",
    "Dodurga",
    "Iskilip",
    "Kargi",
    "Laçin",
    "Mecitozu",
    "Merkez",
    "Ogüzlar",
    "Ortakoy",
    "Osmancik",
    "Sungurlu",
    "Ugurludag",
  ],
  Denizli: [
    "Acipayam",
    "Babadag",
    "Baklan",
    "Bekilli",
    "Beyagac",
    "Bozkurt",
    "Buldan",
    "Cal",
    "Cameli",
    "Cardak",
    "Civril",
    "Guney",
    "Honaz",
    "Kale",
    "Merkezefendi",
    "Pamukkale",
    "Saraykoy",
    "Serinhisar",
    "Tavas",
  ],
  Diyarbakir: [
    "Baglar",
    "Bismil",
    "Cermik",
    "Cinar",
    "Cungus",
    "Dicle",
    "Egil",
    "Ergani",
    "Hani",
    "Hazro",
    "Kayapinar",
    "Kocakoy",
    "Kulp",
    "Lice",
    "Silvan",
    "Sur",
    "Yenisehir",
  ],
  Duzce: [
    "Akcakoca",
    "Cilimli",
    "Cumayeri",
    "Golyaka",
    "Gumusova",
    "Kaynasli",
    "Merkez",
    "Yigilca",
  ],
  Edirne: [
    "Enez",
    "Havsa",
    "Ipsala",
    "Kesan",
    "Lalapasa",
    "Meric",
    "Merkez",
    "Suloglu",
    "Uzunkopru",
  ],
  Elazig: [
    "Agin",
    "Alacakaya",
    "Aricak",
    "Baskil",
    "Karakocan",
    "Keban",
    "Kovancilar",
    "Maden",
    "Merkez",
    "Palu",
    "Sivrice",
  ],
  Erzincan: [
    "Cayirli",
    "Ilic",
    "Kemah",
    "Kemaliye",
    "Merkez",
    "Otlukbeli",
    "Refahiye",
    "Tercan",
    "Uzumlu",
  ],
  Erzurum: [
    "Askale",
    "Aziziye",
    "Cat",
    "Hinis",
    "Horasan",
    "Ilica",
    "Ispir",
    "Karacoban",
    "Karayazi",
    "Koprukoy",
    "Narman",
    "Olur",
    "Oltu",
    "Palandoken",
    "Pasinler",
    "Pazaryolu",
    "Senkaya",
    "Tekman",
    "Tortum",
    "Uzundere",
    "Yakutiye",
  ],
  Eskisehir: [
    "Alpu",
    "Beylikova",
    "Cifteler",
    "Gunyuzu",
    "Han",
    "Inonu",
    "Mahmudiye",
    "Mihaliccik",
    "Mihalgazi",
    "Odunpazari",
    "Saricakaya",
    "Seyitgazi",
    "Sivrihisar",
    "Tepebasi",
  ],
  Gaziantep: [
    "Araban",
    "Islahiye",
    "Karkamis",
    "Nizip",
    "Nurdagi",
    "Oguzeli",
    "Sahinbey",
    "Sehitkamil",
    "Yavuzeli",
  ],
  Giresun: [
    "Alucra",
    "Bulancak",
    "Camoluk",
    "Canakci",
    "Dereli",
    "Dogankent",
    "Espiye",
    "Eynesil",
    "Gorele",
    "Guce",
    "Keşap",
    "Merkez",
    "Piraziz",
    "Sebinkarahisar",
    "Tirebolu",
    "Yaglidere",
  ],
  Gumushane: [
    "Kelkit",
    "Kose",
    "Kurtun",
    "Merkez",
    "Siran",
    "Torul",
  ],
  Hakkari: [
    "Cukurca",
    "Derecik",
    "Merkez",
    "Semdinli",
    "Yuksekova",
  ],
  Hatay: [
    "Altinozu",
    "Antakya",
    "Arsuz",
    "Belen",
    "Defne",
    "Dortyol",
    "Erzin",
    "Hassa",
    "Iskenderun",
    "Kirikhan",
    "Kumlu",
    "Payas",
    "Reyhanli",
    "Samandag",
    "Yayladagi",
  ],
  Igdir: ["Aralik", "Karakoyunlu", "Merkez", "Tuzluca"],
  Isparta: [
    "Aksu",
    "Atabey",
    "Egirdir",
    "Gelendost",
    "Gonen",
    "Keciborlu",
    "Merkez",
    "Senirkent",
    "Sarkikaraagac",
    "Sutculer",
    "Uluborlu",
    "Yalvac",
    "Yenisarbademli",
  ],
  Istanbul: [
    "Adalar",
    "Arnavutkoy",
    "Atasehir",
    "Avcilar",
    "Bagcilar",
    "Bahcelievler",
    "Bakirkoy",
    "Basaksehir",
    "Bayrampasa",
    "Besiktas",
    "Beykoz",
    "Beylikduzu",
    "Beyoglu",
    "Buyukcekmece",
    "Catalca",
    "Cekmekoy",
    "Esenler",
    "Esenyurt",
    "Eyupsultan",
    "Fatih",
    "Gaziosmanpasa",
    "Gungoren",
    "Kadikoy",
    "Kagithane",
    "Kartal",
    "Kucukcekmece",
    "Maltepe",
    "Pendik",
    "Sancaktepe",
    "Sariyer",
    "Silivri",
    "Sultanbeyli",
    "Sultangazi",
    "Sile",
    "Sisli",
    "Tuzla",
    "Umraniye",
    "Uskudar",
    "Zeytinburnu",
  ],
  Izmir: [
    "Aliaga",
    "Balcova",
    "Bayindir",
    "Bayrakli",
    "Bergama",
    "Beydag",
    "Bornova",
    "Buca",
    "Cesme",
    "Cigli",
    "Dikili",
    "Foca",
    "Gaziemir",
    "Guzelbahce",
    "Karabaglar",
    "Karaburun",
    "Karsiyaka",
    "Kemalpasa",
    "Kinik",
    "Kiraz",
    "Konak",
    "Menderes",
    "Menemen",
    "Narlidere",
    "Odemis",
    "Seferihisar",
    "Selcuk",
    "Tire",
    "Torbali",
    "Urla",
  ],
  "Kahramanmaras": [
    "Afsin",
    "Andirin",
    "Caglayancerit",
    "Dulkadiroglu",
    "Ekinozu",
    "Elbistan",
    "Goksun",
    "Nurhak",
    "Onikisubat",
    "Pazarcik",
    "Turkoglu",
  ],
  Karabuk: [
    "Eflani",
    "Eskipazar",
    "Merkez",
    "Ovacik",
    "Safranbolu",
    "Yenice",
  ],
  Karaman: [
    "Ayranci",
    "Basyayla",
    "Ermenek",
    "Kazimkarabekir",
    "Merkez",
    "Sariveliler",
  ],
  Kars: [
    "Akyaka",
    "Arpacay",
    "Digor",
    "Kagizman",
    "Merkez",
    "Sarikamis",
    "Selim",
    "Susuz",
  ],
  Kastamonu: [
    "Abana",
    "Agli",
    "Arac",
    "Azdavay",
    "Bozkurt",
    "Cide",
    "Catalzeytin",
    "Daday",
    "Devrekani",
    "Doganyurt",
    "Hanonu",
    "Ihsangazi",
    "Inebolu",
    "Kure",
    "Merkez",
    "Pinarbasi",
    "Senpazar",
    "Seydiler",
    "Taskopru",
    "Tosya",
  ],
  Kayseri: [
    "Akkisla",
    "Bunyan",
    "Develi",
    "Felahiye",
    "Hacilar",
    "Incesu",
    "Kocasinan",
    "Melikgazi",
    "Ozvatan",
    "Pinarbasi",
    "Sariz",
    "Talas",
    "Tomarza",
    "Yahyali",
    "Yesilhisar",
  ],
  Kirikkale: [
    "Bahsili",
    "Baliseyh",
    "Celebi",
    "Delice",
    "Karakecili",
    "Keskin",
    "Merkez",
    "Sulakyurt",
    "Yahsihan",
  ],
  Kirklareli: [
    "Babaeski",
    "Demirkoy",
    "Kofcaz",
    "Luleburgaz",
    "Merkez",
    "Pehlivankoy",
    "Pinarhisar",
    "Vize",
  ],
  Kirsehir: [
    "Akcakent",
    "Akpinar",
    "Boztepe",
    "Cicekdagi",
    "Kaman",
    "Merkez",
    "Mucur",
  ],
  Kilis: ["Elbeyli", "Merkez", "Musabeyli", "Polateli"],
  Kocaeli: [
    "Basiskele",
    "Cayirova",
    "Darica",
    "Derince",
    "Dilovasi",
    "Gebze",
    "Golcuk",
    "Izmit",
    "Kandira",
    "Karamursel",
    "Kartepe",
    "Korfez",
  ],
  Konya: [
    "Ahirli",
    "Akoren",
    "Aksehir",
    "Altinekin",
    "Beysehir",
    "Bozkir",
    "Cihanbeyli",
    "Celtik",
    "Cumra",
    "Derbent",
    "Derebucak",
    "Doganhisar",
    "Emirgazi",
    "Eregli",
    "Guneysinir",
    "Hadim",
    "Halkapinar",
    "Huyuk",
    "Ilgin",
    "Kadinhani",
    "Karapinar",
    "Karatay",
    "Kulu",
    "Meram",
    "Sarayonu",
    "Selcuklu",
    "Seydisehir",
    "Taskent",
    "Tuzlukcu",
    "Yalihuyuk",
    "Yunak",
  ],
  Kutahya: [
    "Altintas",
    "Aslanapa",
    "Cavdarhisar",
    "Domanic",
    "Dumlupinar",
    "Emet",
    "Gediz",
    "Hisarcik",
    "Merkez",
    "Pazarlar",
    "Simav",
    "Saphane",
    "Tavsanli",
  ],
  Malatya: [
    "Akcadag",
    "Arapgir",
    "Arguvan",
    "Battalgazi",
    "Darende",
    "Dogansehir",
    "Doganyol",
    "Hekimhan",
    "Kale",
    "Kuluncak",
    "Puturge",
    "Yazihan",
    "Yesilyurt",
  ],
  Manisa: [
    "Ahmetli",
    "Akhisar",
    "Alasehir",
    "Demirci",
    "Golmarmara",
    "Gordes",
    "Kirkagac",
    "Koprubasi",
    "Kula",
    "Salihli",
    "Sarigol",
    "Saruhanli",
    "Selendi",
    "Soma",
    "Sehzadeler",
    "Turgutlu",
    "Yunusemre",
  ],
  Mardin: [
    "Artuklu",
    "Dargecit",
    "Derik",
    "Kiziltepe",
    "Mazidagi",
    "Midyat",
    "Nusaybin",
    "Omerli",
    "Savur",
    "Yesilli",
  ],
  Mersin: [
    "Akdeniz",
    "Anamur",
    "Aydincik",
    "Bozyazi",
    "Camliyayla",
    "Erdemli",
    "Gulnar",
    "Mezitli",
    "Mut",
    "Silifke",
    "Tarsus",
    "Toroslar",
    "Yenisehir",
  ],
  Mugla: [
    "Bodrum",
    "Dalaman",
    "Datca",
    "Fethiye",
    "Kavaklidere",
    "Koycegiz",
    "Marmaris",
    "Menteşe",
    "Milas",
    "Ortaca",
    "Seydikemer",
    "Ula",
    "Yatagan",
  ],
  Mus: ["Bulanik", "Hasköy", "Korkut", "Malazgirt", "Merkez", "Varto"],
  Nevsehir: [
    "Acigol",
    "Avanos",
    "Derinkuyu",
    "Gulsehir",
    "Hacibektas",
    "Kozakli",
    "Merkez",
    "Urgup",
  ],
  Nigde: [
    "Altunhisar",
    "Bor",
    "Camardi",
    "Ciftlik",
    "Merkez",
    "Ulukisla",
  ],
  Ordu: [
    "Akkus",
    "Altinordu",
    "Aybasti",
    "Camas",
    "Caybasi",
    "Fatsa",
    "Golkoy",
    "Gulyali",
    "Gurgentepe",
    "Ikizce",
    "Kabaduz",
    "Kabatas",
    "Korgan",
    "Kumru",
    "Mesudiye",
    "Persembe",
    "Ulubey",
    "Unye",
  ],
  Osmaniye: [
    "Bahce",
    "Duzici",
    "Hasanbeyli",
    "Kadirli",
    "Merkez",
    "Sumbas",
    "Toprakkale",
  ],
  Rize: [
    "Ardesen",
    "Camlihemsin",
    "Cayeli",
    "Derepazari",
    "Findikli",
    "Guneysu",
    "Hemsin",
    "Ikizdere",
    "Iyidere",
    "Kalkandere",
    "Merkez",
    "Pazar",
  ],
  Sakarya: [
    "Adapazari",
    "Akyazi",
    "Arifiye",
    "Erenler",
    "Ferizli",
    "Geyve",
    "Hendek",
    "Karapurcek",
    "Karasu",
    "Kaynarca",
    "Kocaali",
    "Pamukova",
    "Sapanca",
    "Serdivan",
    "Sogutlu",
    "Tarakli",
  ],
  Samsun: [
    "Alacam",
    "Asarcik",
    "Atakum",
    "Ayvacik",
    "Bafra",
    "Canik",
    "Carsamba",
    "Havza",
    "Ilkadim",
    "Kavak",
    "Ladik",
    "Ondokuz Mayis",
    "Salipazari",
    "Tekkekoy",
    "Terme",
    "Vezirkopru",
    "Yakakent",
  ],
  Sanliurfa: [
    "Akcakale",
    "Birecik",
    "Bozova",
    "Ceylanpinar",
    "Eyyubiye",
    "Halfeti",
    "Haliliye",
    "Harran",
    "Hilvan",
    "Karakopru",
    "Siverek",
    "Suruc",
    "Viransehir",
  ],
  Siirt: [
    "Baykan",
    "Eruh",
    "Kurtalan",
    "Merkez",
    "Pervari",
    "Sirvan",
    "Tillo",
  ],
  Sinop: [
    "Ayancik",
    "Boyabat",
    "Dikmen",
    "Duragan",
    "Erfelek",
    "Gerze",
    "Merkez",
    "Saraydüzü",
    "Turkeli",
  ],
  Sirnak: [
    "Beytussebap",
    "Cizre",
    "Guclukonak",
    "Idil",
    "Merkez",
    "Silopi",
    "Uludere",
  ],
  Sivas: [
    "Akincilar",
    "Altinyayla",
    "Divrigi",
    "Dogansar",
    "Gemerek",
    "Golova",
    "Gurun",
    "Hafik",
    "Imranli",
    "Kangal",
    "Koyulhisar",
    "Merkez",
    "Susehri",
    "Sarkisla",
    "Ulas",
    "Yildizeli",
    "Zara",
  ],
  Tekirdag: [
    "Cerkezkoy",
    "Corlu",
    "Ergene",
    "Hayrabolu",
    "Kapakli",
    "Malkara",
    "Marmaraereglisi",
    "Muratli",
    "Saray",
    "Sarkoy",
    "Suleymanpasa",
  ],
  Tokat: [
    "Almus",
    "Artova",
    "Basciftlik",
    "Erbaa",
    "Merkez",
    "Niksar",
    "Pazar",
    "Resadiye",
    "Sulusaray",
    "Turhal",
    "Yesilyurt",
    "Zile",
  ],
  Trabzon: [
    "Akcaabat",
    "Araklı",
    "Arsin",
    "Besikduzu",
    "Caykara",
    "Dernekpazari",
    "Duzkoy",
    "Hayrat",
    "Koprubasi",
    "Macka",
    "Of",
    "Ortahisar",
    "Salpazari",
    "Sürmene",
    "Surat",
    "Tonya",
    "Vakfikebir",
    "Yomra",
  ],
  Tunceli: [
    "Cemisgezek",
    "Hozat",
    "Mazgirt",
    "Merkez",
    "Nazimiye",
    "Ovacik",
    "Pertek",
    "Pulumur",
  ],
  Usak: [
    "Banaz",
    "Esme",
    "Karahalli",
    "Merkez",
    "Sivasli",
    "Ulubey",
  ],
  Van: [
    "Baskale",
    "Caldiran",
    "Catak",
    "Edremit",
    "Ercis",
    "Gevas",
    "Gurpinar",
    "Ipekyolu",
    "Muradiye",
    "Ozalp",
    "Saray",
    "Tusba",
  ],
  Yalova: [
    "Altinova",
    "Armutlu",
    "Ciftlikkoy",
    "Cinarcik",
    "Merkez",
    "Termal",
  ],
  Yozgat: [
    "Akdagmadeni",
    "Aydincik",
    "Bogazliyan",
    "Caydinci",
    "Cekerek",
    "Kadisehri",
    "Merkez",
    "Saraykent",
    "Sarikaya",
    "Sefaatli",
    "Sorgun",
    "Yenifakili",
    "Yerkoy",
  ],
  Zonguldak: [
    "Alapli",
    "Caycuma",
    "Devrek",
    "Eregli",
    "Gokcebey",
    "Kilimli",
    "Kozlu",
    "Merkez",
  ],
}

export const TR_PROVINCES: string[] = Object.keys(TR_PROVINCES_MAP).sort(
  (a, b) => a.localeCompare(b, "tr"),
)

export function getDistricts(province: string): string[] {
  return TR_PROVINCES_MAP[province] ?? []
}

// -----------------------------
// OpenStreetMap / Nominatim entegrasyonu
// -----------------------------

const NOMINATIM_BASE = "https://nominatim.openstreetmap.org"

export interface GeocodeResult {
  lat: number
  lng: number
  displayName: string
}

export interface NeighborhoodSuggestion {
  name: string
  displayName: string
  lat: number
  lng: number
}

function normalizeTR(value: string) {
  return value
    .toLocaleLowerCase("tr-TR")
    .replaceAll("ı", "i")
    .replaceAll("ğ", "g")
    .replaceAll("ü", "u")
    .replaceAll("ş", "s")
    .replaceAll("ö", "o")
    .replaceAll("ç", "c")
    .replaceAll("İ", "i")
    .trim()
}

const DIYARBAKIR_NEIGHBORHOODS: Record<string, string[]> = {
  Baglar: [
    "5 Nisan",
    "Alipınar",
    "Bağcılar",
    "Batıkent",
    "Fatih",
    "Kaynartepe",
    "Mevlana Halit",
    "Muradiye",
    "Selahattin Eyyubi",
    "Şeyh Şamil",
    "Yeniköy",
    "Yunus Emre",
  ],
  Kayapinar: [
    "Barış",
    "Diclekent",
    "Fırat",
    "Huzurevleri",
    "Medya",
    "Mezopotamya",
    "Peyas",
    "Talaytepe",
    "Urfa Yolu",
    "Yolboyu",
  ],
  Sur: [
    "Alipaşa",
    "Cami Nebi",
    "Cemal Yılmaz",
    "Dabanoğlu",
    "Dicle",
    "Fatihpaşa",
    "Hasırlı",
    "İskenderpaşa",
    "Lalebey",
    "Melikahmet",
    "Savaş",
    "Suriçi",
    "Ziya Gökalp",
  ],
  Yenisehir: [
    "Aziziye",
    "Cumhuriyet",
    "Dicle",
    "Dokuzçeltik",
    "Fabrika",
    "Kooperatifler",
    "Ofis",
    "Sanayi",
    "Seyrantepe",
    "Şehitlik",
    "Üçkuyu",
    "Yenişehir",
  ],
}

function getLocalNeighborhoods(
  province: string,
  district: string,
  query: string,
): NeighborhoodSuggestion[] {
  const provinceKey = normalizeTR(province)
  const districtKey = normalizeTR(district)
  const q = normalizeTR(query)

  if (provinceKey !== "diyarbakir") return []

  const matchedDistrictKey = Object.keys(DIYARBAKIR_NEIGHBORHOODS).find(
    (key) => normalizeTR(key) === districtKey,
  )

  if (!matchedDistrictKey) return []

  return DIYARBAKIR_NEIGHBORHOODS[matchedDistrictKey]
    .filter((name) => normalizeTR(name).includes(q))
    .slice(0, 20)
    .map((name) => ({
      name,
      displayName: `${name} Mahallesi, ${district}, ${province}`,
      lat: Number.NaN,
      lng: Number.NaN,
    }))
}

export async function geocodeAddress(
  address: string,
  province?: string,
  district?: string,
  signal?: AbortSignal,
): Promise<GeocodeResult | null> {
  const trimmed = address.trim()
  if (!trimmed) return null

  const parts = [trimmed, district, province, "Turkey"].filter(Boolean).join(", ")
  const params = new URLSearchParams({
    q: parts,
    format: "json",
    addressdetails: "0",
    limit: "1",
    countrycodes: "tr",
  })

  try {
    const res = await fetch(`${NOMINATIM_BASE}/search?${params.toString()}`, {
      method: "GET",
      headers: { Accept: "application/json" },
      signal,
    })

    if (!res.ok) return null

    const data = (await res.json()) as Array<{
      lat: string
      lon: string
      display_name: string
    }>

    if (!Array.isArray(data) || data.length === 0) return null

    const first = data[0]
    const lat = Number(first.lat)
    const lng = Number(first.lon)

    if (!Number.isFinite(lat) || !Number.isFinite(lng)) return null

    return {
      lat,
      lng,
      displayName: first.display_name,
    }
  } catch {
    return null
  }
}

export async function searchNeighborhoods(
  province: string,
  district: string,
  query: string,
  signal?: AbortSignal,
): Promise<NeighborhoodSuggestion[]> {
  const q = query.trim()
  if (q.length < 2 || !province || !district) return []

  const localResults = getLocalNeighborhoods(province, district, q)
  if (localResults.length > 0) return localResults

  const params = new URLSearchParams({
    q: `${q} Mahallesi, ${district}, ${province}, Turkey`,
    format: "json",
    countrycodes: "tr",
    addressdetails: "1",
    limit: "10",
  })

  try {
    const res = await fetch(`${NOMINATIM_BASE}/search?${params.toString()}`, {
      method: "GET",
      headers: { Accept: "application/json" },
      signal,
    })

    if (!res.ok) return []

    const data = (await res.json()) as Array<{
      lat: string
      lon: string
      display_name: string
      address?: {
        suburb?: string
        neighbourhood?: string
        quarter?: string
        village?: string
        hamlet?: string
        road?: string
      }
    }>

    const seen = new Set<string>()
    const suggestions: NeighborhoodSuggestion[] = []

    for (const item of data) {
      const addr = item.address ?? {}

      const name =
        addr.neighbourhood ||
        addr.suburb ||
        addr.quarter ||
        addr.village ||
        addr.hamlet ||
        addr.road ||
        ""

      if (!name) continue

      const key = normalizeTR(name)
      if (seen.has(key)) continue

      seen.add(key)

      suggestions.push({
        name,
        displayName: item.display_name,
        lat: Number(item.lat),
        lng: Number(item.lon),
      })
    }

    return suggestions
  } catch {
    return []
  }
}
